import puppeteer from '/Users/sugengrifqimubaroq/.npm/_npx/2978c56d194a0f5a/node_modules/puppeteer/lib/esm/puppeteer/puppeteer.js';
const errors=[]; let nativeConfirmFired=false;
const b = await puppeteer.launch({ headless:true, args:['--no-sandbox'] });
const p = await b.newPage();
p.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
p.on('pageerror',e=>errors.push('PAGEERR: '+e.message));
p.on('dialog', async d=>{ nativeConfirmFired=true; await d.dismiss(); });
await p.goto('http://localhost:5199/', { waitUntil:'networkidle2' });
await p.waitForSelector('#ob-form');
await p.type('#ob-name','Rara'); await p.type('#ob-school','SDN Mekar Jaya 1'); await p.select('#ob-class','5A');
await p.click('#ob-form button[type=submit]');
await p.waitForSelector('#vm-shell:not(.hidden)');
await p.evaluate(()=> window.vmLogout());
await new Promise(r=>setTimeout(r,300));
const dialogAda = await p.evaluate(()=> !!document.querySelector('[role="dialog"]'));
const adaMaskot = await p.evaluate(()=> !!document.querySelector('[role=dialog] .ph-bird'));
console.log('Dialog kustom muncul:', dialogAda, '| ada maskot:', adaMaskot);
await p.evaluate(()=>{ [...document.querySelectorAll('[role=dialog] button')].find(b=>/batal/i.test(b.textContent)).click(); });
await new Promise(r=>setTimeout(r,300));
const masihLogin = await p.evaluate(()=> !document.getElementById('vm-shell').classList.contains('hidden'));
console.log('Setelah BATAL → masih di app:', masihLogin);
await p.evaluate(()=> window.vmLogout());
await new Promise(r=>setTimeout(r,300));
await p.evaluate(()=>{ [...document.querySelectorAll('[role=dialog] button')].find(b=>/keluar/i.test(b.textContent)).click(); });
await p.waitForSelector('#ob-form', { timeout:5000 });
console.log('Setelah YA → kembali ke onboarding: true');
await b.close();
if(nativeConfirmFired) errors.push('confirm bawaan masih terpanggil');
if(!dialogAda) errors.push('dialog kustom tidak muncul');
if(!masihLogin) errors.push('BATAL malah keluar');
if(errors.length){ console.log('FAIL: '+errors.join(' | ')); process.exit(1);}
console.log('OK: dialog kustom muncul, BATAL aman, YA keluar; tanpa confirm bawaan, tanpa error.');
